#%RAML 1.0 Trait
queryParameters:
  departureLocation:
    description: The departure location code, selected by the customer.
    required: false
    type: string
    example: "BEN-SG"
  destinationLocation:
    description: The destination location code, selected by the customer.
    required: false
    type: string
    example: "KLG-MY"